name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: "Default"
            append:
          - name: "HOTFIRE_TEST"
            append: export HOTFIRE_TEST=1;
          - name: "USE_SBG"
            append: export USE_SBG=1;
          - name: "SKIP_INIT"
            append: export SKIP_INIT=1;
          - name: "HOTFIRE_TEST and SKIP_INIT"
            append: export HOTFIRE_TEST=1; export SKIP_INIT=1;
          - name: "TESTING"
            append: export TESTING=1;
          - name: "HOTFIRE_TEST and TESTING"
            append: export HOTFIRE_TEST=1; export TESTING=1;
          - name: "USE_SOCKET_CLIENT"
            append: export USE_SOCKET_CLIENT=1;

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      # Build the project
      - name: Install dependencies
        run: sudo ./install-dependencies.sh
      - name: "${{ matrix.name }}: Build"
        run: ${{ matrix.append }} ./build.sh
