name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: "Default"
            append:
          - name: "HOTFIRE_TEST"
            append: export HOTFIRE_TEST=1;
          - name: "USE_SBG"
            append: export USE_SBG=1;
          - name: "SKIP_INIT"
            append: export SKIP_INIT=1;
          - name: "HOTFIRE_TEST and SKIP_INIT"
            append: export HOTFIRE_TEST=1; export SKIP_INIT=1;
          - name: "TESTING"
            append: export TESTING=1;
          - name: "HOTFIRE_TEST and TESTING"
            append: export HOTFIRE_TEST=1; export TESTING=1;
          - name: "USE_SOCKET_CLIENT"
            append: export USE_SOCKET_CLIENT=1;

    steps:
      # Initialization
      - name: Install SSH Key # For private submodules
        run: mkdir -p$HOME/.ssh && echo "${{ secrets.SSH_KEY }}" > $HOME/.ssh/id_rsa && chmod 600 $HOME/.ssh/id_rsa
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Force Git to use SSH
        run: git config --global url.ssh://git@github.com/.insteadOf https://github.com/
      # Build the project
      - name: Install dependencies
        run: sudo ./install-dependencies.sh
      - name: "${{ matrix.name }}: Cmake Makefiles"
        run: ${{ matrix.append }} cmake -B ./build -G 'Unix Makefiles'
      - name: "${{ matrix.name }}: Run make"
        run: ${{ matrix.append }} cmake --build ./build --target MainLoop
