name: End-to-end

on: [push, pull_request]

jobs:
  OctoberSky1:
    name: OctoberSky1
    runs-on: ubuntu-latest
    

    steps:
      # Initialization
      - name: Install SSH Key # For private submodules
        run: mkdir -p $HOME/.ssh && echo "${{ secrets.SSH_KEY }}" > $HOME/.ssh/id_rsa && chmod 600 $HOME/.ssh/id_rsa
      - name: Force Git to use SSH
        run: git config --global url.ssh://git@github.com/.insteadOf https://github.com/
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install dependencies
        run: sudo ./install-dependencies.sh
      - name: Git reset
        run: git reset --hard
      - name: Run OctoberSky1 Test
        run: cd ./tests/octoberSky/; bash ./run_test.sh "Unix Makefiles"