name: End-to-end

on: [push, pull_request]

jobs:
  OctoberSky1:
    name: OctoberSky1
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3

      - name: Install Conan
        run: pip install conan

      - name: Create conan profile
        run: |
          conan profile new default --detect
          conan profile update settings.compiler.libcxx=libstdc++11 default

      - name: Install dependencies
        run: |
          apt-fast update
          apt-fast install ninja-build libsystemd-dev -y        

      - name: Run OctoberSky1 Test
        run: cd ./tests/octoberSky && ./run_test.sh
