name: Unit Testing

on: [push, pull_request]

jobs:
  unit_testing:
    name: Unit Testing
    runs-on: ubuntu-latest

    steps:
      # Initialization
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install dependencies
        run: sudo ./install-dependencies.sh
      - name: Cmake Makefiles
        run: USE_GPIO=1 cmake -B ./build -G 'Unix Makefiles'
      - name: Run make
        run: USE_GPIO=1 cmake --build ./build --target tests
      - name: Run Unit Tests
        run: ./build/unitTesting/tests
